CREATE TABLE section (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(50) NOT NULL UNIQUE,
    daily_required_hours  INTEGER      NOT NULL CHECK (daily_required_hours > 0)
);