CREATE TABLE worker (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(20) NOT NULL,
    last_name       VARCHAR(40) NOT NULL,
    dni             VARCHAR(9)   NOT NULL UNIQUE,
    contract_hours  INTEGER      NOT NULL CHECK (contract_hours > 0 AND contract_hours <= 8),
    store_id        BIGINT       NOT NULL REFERENCES store(id)
);