CREATE TABLE store_section (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id    BIGINT NOT NULL REFERENCES store(id),
    section_id  BIGINT NOT NULL REFERENCES section(id),
    UNIQUE (store_id, section_id)
);