CREATE TABLE worker_section_assignment (
    id                 BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id          BIGINT  NOT NULL REFERENCES worker(id),
    store_section_id   BIGINT  NOT NULL REFERENCES store_section(id),
    assigned_hours     INTEGER NOT NULL CHECK (assigned_hours > 0),
    UNIQUE (worker_id, store_section_id)
);